/*
 * Created on 2020-07-10 ( Time 09:27:28 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package pl.wasko.time.manager.rest.api.model.entity;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "CoOwners" ( stored in table "co_owners" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class CoOwnerKey implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="user_id", nullable=false)
    private Integer    userId       ;
    
    @Column(name="bucket_id", nullable=false)
    private Integer    bucketId     ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public CoOwnerKey()
    {
        super();
    }

    public CoOwnerKey(Integer userId, Integer bucketId )
    {
        super();
        this.userId = userId ;
        this.bucketId = bucketId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setUserId( Integer value )
    {
        this.userId = value;
    }
    public Integer getUserId()
    {
        return this.userId;
    }

    public void setBucketId( Integer value )
    {
        this.bucketId = value;
    }
    public Integer getBucketId()
    {
        return this.bucketId;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		CoOwnerKey other = (CoOwnerKey) obj;
		//--- Attribute userId
		if ( userId == null ) { 
			if ( other.userId != null ) 
				return false ; 
		} else if ( ! userId.equals(other.userId) ) 
			return false ; 
		//--- Attribute bucketId
		if ( bucketId == null ) { 
			if ( other.bucketId != null ) 
				return false ; 
		} else if ( ! bucketId.equals(other.bucketId) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute userId
		result = prime * result + ((userId == null) ? 0 : userId.hashCode() ) ; 
		//--- Attribute bucketId
		result = prime * result + ((bucketId == null) ? 0 : bucketId.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
		StringBuffer sb = new StringBuffer(); 
		sb.append(userId); 
		sb.append("|"); 
		sb.append(bucketId); 
        return sb.toString();
    }
}