/*
 * Created on 2020-07-10 ( Time 09:27:29 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package pl.wasko.time.manager.rest.api.model.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "positions"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="positions")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Positions.countAll", query="SELECT COUNT(x) FROM Position x" )
} )
public class Position implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id_position", nullable=false)
    private Integer    idPosition   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="position_name", nullable=false, length=255)
    private String     positionName ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="position", targetEntity= User.class)
    private List<User> listOfUsers ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Position()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdPosition( Integer idPosition )
    {
        this.idPosition = idPosition ;
    }
    public Integer getIdPosition()
    {
        return this.idPosition;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : position_name ( VARCHAR ) 
    public void setPositionName( String positionName )
    {
        this.positionName = positionName;
    }
    public String getPositionName()
    {
        return this.positionName;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfUsers( List<User> listOfUsers )
    {
        this.listOfUsers = listOfUsers;
    }
    public List<User> getListOfUsers()
    {
        return this.listOfUsers;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idPosition);
        sb.append("]:"); 
        sb.append(positionName);
        return sb.toString(); 
    } 

}
