/*
 * Created on 2020-07-10 ( Time 09:27:29 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package pl.wasko.time.manager.rest.api.model.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "priorities"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="priorities")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Priorities.countAll", query="SELECT COUNT(x) FROM Priority x" )
} )
public class Priority implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id_priority", nullable=false)
    private Integer    idPriority   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="priority", nullable=false, length=255)
    private String     priority     ;


    @Column(name="notification_time", nullable=false)
    private String notificationTime ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="priority", targetEntity= Task.class)
    private List<Task> listOfTasks ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Priority()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdPriority( Integer idPriority )
    {
        this.idPriority = idPriority ;
    }
    public Integer getIdPriority()
    {
        return this.idPriority;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : priority ( VARCHAR ) 
    public void setPriority( String priority )
    {
        this.priority = priority;
    }
    public String getPriority()
    {
        return this.priority;
    }

    //--- DATABASE MAPPING : notification_time ( INT )

    public void setNotificationTime( String notificationTime )
    {
        this.notificationTime = notificationTime;
    }
    public String getNotificationTime()
    {
        return this.notificationTime;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfTasks( List<Task> listOfTasks )
    {
        this.listOfTasks = listOfTasks;
    }
    public List<Task> getListOfTasks()
    {
        return this.listOfTasks;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idPriority);
        sb.append("]:"); 
        sb.append(priority);
        sb.append("|");
        sb.append(notificationTime);
        return sb.toString(); 
    } 

}
