/*
 * Created on 2020-07-10 ( Time 09:27:29 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package pl.wasko.time.manager.rest.api.model.entity;

import pl.wasko.time.manager.rest.api.model.enumeration.RoleEnum;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "roles"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="roles")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Roles.countAll", query="SELECT COUNT(x) FROM Role x" )
} )
public class Role implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id_role", nullable=false)
    private Integer    idRole       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="role_name", nullable=false, length=255)
    @Enumerated(EnumType.STRING)
    private RoleEnum roleName     ;

    @Column(name="max_buckets", nullable=false)
    private Integer    maxBuckets   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="role", targetEntity= User.class)
    private List<User> listOfUsers ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Role()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdRole( Integer idRole )
    {
        this.idRole = idRole ;
    }
    public Integer getIdRole()
    {
        return this.idRole;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : role_name ( VARCHAR ) 


    public RoleEnum getRoleName() {
        return roleName;
    }

    public void setRoleName(RoleEnum roleName) {
        this.roleName = roleName;
    }

    //--- DATABASE MAPPING : max_buckets ( INT )
    public void setMaxBuckets( Integer maxBuckets )
    {
        this.maxBuckets = maxBuckets;
    }
    public Integer getMaxBuckets()
    {
        return this.maxBuckets;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfUsers( List<User> listOfUsers )
    {
        this.listOfUsers = listOfUsers;
    }
    public List<User> getListOfUsers()
    {
        return this.listOfUsers;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idRole);
        sb.append("]:"); 
        sb.append(roleName);
        sb.append("|");
        sb.append(maxBuckets);
        return sb.toString(); 
    } 

}
