/*
 * Created on 2020-07-10 ( Time 09:27:29 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package pl.wasko.time.manager.rest.api.model.entity;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "Shares" ( stored in table "shares" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class ShareKey implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="user_id", nullable=false)
    private Integer    userId       ;
    
    @Column(name="task_id", nullable=false)
    private Integer    taskId       ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public ShareKey()
    {
        super();
    }

    public ShareKey(Integer userId, Integer taskId )
    {
        super();
        this.userId = userId ;
        this.taskId = taskId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setUserId( Integer value )
    {
        this.userId = value;
    }
    public Integer getUserId()
    {
        return this.userId;
    }

    public void setTaskId( Integer value )
    {
        this.taskId = value;
    }
    public Integer getTaskId()
    {
        return this.taskId;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		ShareKey other = (ShareKey) obj;
		//--- Attribute userId
		if ( userId == null ) { 
			if ( other.userId != null ) 
				return false ; 
		} else if ( ! userId.equals(other.userId) ) 
			return false ; 
		//--- Attribute taskId
		if ( taskId == null ) { 
			if ( other.taskId != null ) 
				return false ; 
		} else if ( ! taskId.equals(other.taskId) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute userId
		result = prime * result + ((userId == null) ? 0 : userId.hashCode() ) ; 
		//--- Attribute taskId
		result = prime * result + ((taskId == null) ? 0 : taskId.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
		StringBuffer sb = new StringBuffer(); 
		sb.append(userId); 
		sb.append("|"); 
		sb.append(taskId); 
        return sb.toString();
    }
}