/*
 * Created on 2020-07-10 ( Time 09:27:29 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a composite Primary Key  


package pl.wasko.time.manager.rest.api.model.entity;

import org.hibernate.annotations.Where;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "shares"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="shares")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Shares.countAll", query="SELECT COUNT(x) FROM Share x" )
} )
public class Share implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private ShareKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------

    @Column(name="deleted", nullable=false)
    private Boolean    deleted      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="task_id", referencedColumnName="id_task", insertable=false, updatable=false)
    private Task task;

    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id_user", insertable=false, updatable=false)
    private User user;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Share()
    {
		super();
		this.compositePrimaryKey = new ShareKey();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------

    public Integer getUserId()
    {
        return this.compositePrimaryKey.getUserId() ;
    }

    public Integer getTaskId()
    {
        return this.compositePrimaryKey.getTaskId() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //--- DATABASE MAPPING : deleted ( BIT ) 
    public void setDeleted( Boolean deleted )
    {
        this.deleted = deleted;
    }
    public Boolean getDeleted()
    {
        return this.deleted;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTask(Task task)
    {
        this.task = task;
        this.compositePrimaryKey.setTaskId(task.getIdTask());
    }
    public Task getTask()
    {
        return this.task;
    }

    public void setUser(User user)
    {
        this.user = user;
        this.compositePrimaryKey.setUserId(user.getIdUser());
    }
    public User getUser()
    {
        return this.user;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:");
        sb.append(deleted);
        return sb.toString(); 
    } 

}
