/*
 * Created on 2020-07-10 ( Time 09:27:29 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package pl.wasko.time.manager.rest.api.model.entity;

import org.hibernate.annotations.Where;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "subscriptions"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="subscriptions")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Subscriptions.countAll", query="SELECT COUNT(x) FROM Subscription x" )
} )
public class Subscription implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id_sub", nullable=false)
    private Integer    idSub        ;


	// "emailId" (column "email_id") is not defined by itself because used as FK in a link 
	// "taskId" (column "task_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="task_id", referencedColumnName="id_task")
    private Task task;

    @ManyToOne
    @JoinColumn(name="email_id", referencedColumnName="id_email")
    private Email email;

    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id_user")
    private User user;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Subscription()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdSub( Integer idSub )
    {
        this.idSub = idSub ;
    }
    public Integer getIdSub()
    {
        return this.idSub;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTask(Task task)
    {
        this.task = task;
    }
    public Task getTask()
    {
        return this.task;
    }

    public void setEmail(Email email)
    {
        this.email = email;
    }
    public Email getEmail()
    {
        return this.email;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idSub);
        sb.append("]:");
        return sb.toString(); 
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Boolean isUserOwner(User user) {
        return this.user.equals(user);
    }
}
